skip_branch_with_pr: true
image: Visual Studio 2019
platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

install:
  - cinst gitversion.portable -y
  - if not exist gtk-sharp-2.12.45.msi appveyor DownloadFile https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.45.msi
  - msiexec /i gtk-sharp-2.12.45.msi /qn /norestart
  - if not exist gtk-sharp-2.99.3.msi appveyor DownloadFile https://download.gnome.org/binaries/win32/gtk-sharp/2.99/gtk-sharp-2.99.3.msi
  - msiexec /i gtk-sharp-2.99.3.msi /qn /norestart

cache:
  - gtk-sharp-2.12.45.msi
  - gtk-sharp-2.99.3.msi

before_build:
  - NuGet restore Source/OxyPlot.AppVeyor.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Source/OxyPlot.AppVeyor.sln
  verbosity: minimal
 
artifacts:
  - path: '**/*.nupkg'

deploy:
  provider: NuGet
  server: https://www.myget.org/F/oxyplot/api/v2/package
  api_key:
    secure: 2GnqgfpkOUH6Umfn1WWlun0b021+QeInBXkgQOQfa4/wDOYHLT757rrjTsb0lmon
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
